version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: connect-four-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: connect_four
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - connect-four-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: connect-four-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - connect-four-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: connect-four-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - connect-four-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: connect-four-backend
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - connect-four-network

volumes:
  postgres_data:

networks:
  connect-four-network:
    driver: bridge
